version: '3'
services:

  web:
    image: nginx
    volumes:
      - '.:/var/www/html'
      - './docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf'

    ports:
      - "81:80"
  php-fpm:
    build: ./docker
    volumes:
      - './docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - '.:/var/www/html'
    env_file:
      - .env

  db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      ports:
          - "5672:5672"       # RabbitMQ port
          - "15672:15672"     # Management UI port
      environment:
          RABBITMQ_DEFAULT_USER: abelesense
          RABBITMQ_DEFAULT_PASS: 2410
